Repository nbcamp-mot/puppy-ground, pull requests merged in 2024-01, with the labels that each got.

#13 [chore/supabase] supabase 세팅
  src/shared/supabase/supabase.ts
  src/shared/supabase/types/supabase.d.ts
Labels: 🔧 설정

#15 feat: layout UI, 페이지 연결
  public/logo.png
  src/app/_components/layout/Footer.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/footer.module.scss
  src/app/_components/layout/header.module.scss
  src/app/layout.tsx
Labels: ✨ 기능, 💄 UI

#16 [chore/db] supabase used_item과 location 테이블 병합
  src/shared/supabase/types/supabase.d.ts
Labels: 🔧 설정

#17 [feat/used-map] 카카오맵 지도로 장소 마커 기능
  .prettierrc
  package.json
  public/images/logo.png
  src/app/_components/kakaoMap/KakaoMapMarker.module.scss
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/_components/layout/Footer.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/footer.module.scss
  src/app/facilities/page.module.scss
  src/app/layout.tsx
  src/app/used-goods/page.tsx
  src/app/variables.css
  src/hooks/useToast.ts
  src/shared/supabase/types/supabase.d.ts
  tsconfig.json
  yarn.lock
Labels: ✨ 기능

#19 [Feat/chatting] 실시간 채팅 기능
  package.json
  src/app/_components/chatting/Chat.tsx
  src/app/_components/chatting/ChatModal.tsx
  src/app/_components/chatting/chat.module.scss
  src/app/_components/chatting/chatModal.module.scss
  src/app/_components/layout/Header.tsx
  src/app/layout.tsx
  src/shared/supabase/types/supabase.d.ts
  yarn.lock
Labels: ✨ 기능, 📈 깃, 💄 UI

#21 [feat/used-list] Supabase API 응답을 받아와서 중고 물품 목록 화면 표시
  .prettierrc
  next.config.js
  src/app/used-goods/_components/UsedGoodsItem.tsx
  src/app/used-goods/_components/UsedGoodsListFilter.tsx
  src/app/used-goods/_components/index.ts
  src/app/used-goods/_components/usedGoodsItem.module.scss
  src/app/used-goods/page.module.scss
  src/app/used-goods/page.tsx
  src/utils/table.ts
  src/utils/time.ts
Labels: ✨ 기능, 🔧 설정

#26 Feat/login
  package.json
  src/app/_components/layout/Header.tsx
  src/app/auth/login/page.module.scss
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.module.scss
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/hooks/useUserInfo.ts
  yarn.lock
Labels: ✨ 기능, 📝 문서

#28 [feat/used-detail] 중고 물품 상세 페이지 구현
  package.json
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/layout.tsx
  src/app/used-goods/[id]/page.module.scss
  src/app/used-goods/[id]/page.tsx
  src/app/used-goods/_components/SlideImage.tsx
  src/app/used-goods/_components/TradeLocationMap.tsx
  src/app/used-goods/_components/index.ts
  src/app/used-goods/_components/slideImage.module.scss
  src/app/used-goods/page.tsx
  src/app/variables.css
  src/utils/time.ts
  yarn.lock
Labels: ✨ 기능, 💄 UI, 🔧 설정

#33 [feat/profiles] 프로필 수정 기능
  src/apis/profile/profile.ts
  src/app/_components/layout/Header.tsx
  src/app/profile/[userId]/page.module.scss
  src/app/profile/[userId]/page.tsx
  src/app/profile/[username]/page.tsx
Labels: ✨ 기능, 📈 깃

#36 [Feat/login] 파일 디렉토리 구조 변경, 유저정보 전역관리 로직 변경
  next.config.js
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/facilities/[id]/page.tsx
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/layout.tsx
  src/app/(providers)/mungstagram/page.tsx
  src/app/(providers)/page.module.scss
  src/app/(providers)/page.tsx
  src/app/(providers)/profile/[userId]/page.module.scss
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/stray-dogs/[id]/page.tsx
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/SlideImage.tsx
  src/app/(providers)/used-goods/_components/TradeLocationMap.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsItem.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsListFilter.tsx
  src/app/(providers)/used-goods/_components/index.ts
  src/app/(providers)/used-goods/_components/slideImage.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsItem.module.scss
  src/app/(providers)/used-goods/create/CreateForm.tsx
  src/app/(providers)/used-goods/create/create.module.scss
  src/app/(providers)/used-goods/create/page.tsx
  src/app/(providers)/used-goods/page.module.scss
  src/app/(providers)/used-goods/page.tsx
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
  src/app/(providers)/used-goods/update/[id]/page.tsx
  src/app/(providers)/used-goods/update/[id]/update.module.scss
  src/app/_components/layout/Header.tsx
  src/app/auth/login/page.module.scss
  src/app/layout.tsx
  src/hooks/useAuth.ts
  zustand/useUserInfo.ts
Labels: 🐛 버그, 🎨 코드 개선, 📈 깃

#35 [feat/used-list] 중고 물품 실시간 조회 및 필터링
  package.json
  src/app/(providers)/layout.tsx
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsFilter.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsItem.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsListFilter.tsx
  src/app/(providers)/used-goods/_components/index.ts
  src/app/(providers)/used-goods/actions.ts
  src/app/(providers)/used-goods/page.module.scss
  src/app/(providers)/used-goods/page.tsx
  src/app/_components/layout/index.ts
  yarn.lock
Labels: ✨ 기능

#37 [feat/share] 공유하기
  src/apis/supabase.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/shareButton/ClipBoardButton.tsx
  src/app/_components/shareButton/KakaoShareButton.tsx
Labels: ✨ 기능, 📈 깃

#40 [Feat/stray-dogs] 반려동물 동반가능시설 지도, 유기견 공고 리스트 및 상세페이지
  next.config.js
  package.json
  public/images/image_processing20210911-6827-1lzc0fb-ezgif.com-effects.gif
  public/logo.png
  src/apis/facilities.ts
  src/apis/stray.ts
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/facilities/[id]/page.tsx
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/stray-dogs/[desertionNo]/page.module.scss
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/(providers)/stray-dogs/[id]/page.tsx
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/_components/facilities/NearFacilities.tsx
  src/app/_components/facilities/nearFacilities.module.scss
  src/app/_components/kakaoMap/KakaoMapMarker.module.scss
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/footer.module.scss
  src/app/_components/layout/header.module.scss
  src/app/_components/layout/loading/Loading.tsx
  src/app/_components/layout/loading/loading.module.scss
  src/app/globals.css
  src/app/not-found.tsx
  src/data/regionList.json
  src/hooks/useFacilitiesQuery.ts
  src/hooks/useToast.ts
  src/shared/strayList.d.ts
  src/shared/supabase/types/supabase.d.ts
  yarn.lock
Labels: ✨ 기능, 💄 UI

#42 [feat/sold-out] sold-out 기능 구현
  src/apis/used-goods/actions.ts
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
Labels: ✨ 기능

#45 [feat/search] 중고 물품 목록 검색
  src/app/(providers)/used-goods/_components/UsedGoodsFilter.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/actions.ts
  src/app/(providers)/used-goods/page.tsx
Labels: ✨ 기능

#47 [feat/create-map] 중고물품 등록페이지에 마커 위치정보 zustand로 관리
  src/app/(providers)/stray-dogs/[desertionNo]/page.module.scss
  src/app/(providers)/used-goods/create/CreateForm.tsx
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/hooks/useKakaoMapMarker.ts
Labels: 🎨 코드 개선

#48 [feat/chatting] 실시간 채팅
  src/apis/chat/chat.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/chatting/Chat.tsx
  src/app/_components/chatting/ChatInput.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/chat.module.scss
  src/app/_components/chatting/chatInput.module.scss
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/chatting/chatModal.module.scss
  src/app/_components/layout/Header.tsx
  src/shared/supabase/types/supabase.d.ts
Labels: 🐛 버그, ✨ 기능, 📈 깃, 💄 UI

#49 [feat/chatting] 실시간 채팅
  src/apis/chat/chat.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/chatList.module.scss
Labels: ✨ 기능

#51 [design/used-list] 디자인 반영한 중고 물품 목록 UI
  package.json
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/Dropdown.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsFilter.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsItem.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsOrder.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsSearch.tsx
  src/app/(providers)/used-goods/_components/dropdown.module.scss
  src/app/(providers)/used-goods/_components/index.ts
  src/app/(providers)/used-goods/_components/usedGoodsFilter.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsItem.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsList.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsOrder.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsSearch.module.scss
  src/app/(providers)/used-goods/page.module.scss
  src/app/(providers)/used-goods/page.tsx
  src/app/variables.css
  src/hooks/useQueryParam.ts
  src/utils/format.ts
  yarn.lock
Labels: 🎨 코드 개선, 💄 UI, 🔧 설정

#56 [design/stray-dog] 유기견공고 페이지 디자인 작업
  next.config.js
  package.json
  public/fonts/GmarketSansBold.otf
  public/fonts/Pretendard-Bold.otf
  public/fonts/Pretendard-ExtraBold.otf
  public/fonts/Pretendard-Light.otf
  public/fonts/Pretendard-Medium.otf
  public/fonts/Pretendard-Regular.otf
  public/fonts/Pretendard-SemiBold.otf
  public/images/kakaoLogo.png
  src/apis/stray.ts
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/layout.tsx
  src/app/(providers)/stray-dogs/[desertionNo]/page.module.scss
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/footer.module.scss
  src/app/_components/layout/header.module.scss
  src/app/_components/main/MainGrid.tsx
  src/app/_components/main/mainGrid.module.scss
  src/app/_components/pagination/Pagination.tsx
  src/app/_components/pagination/pagination.module.scss
  src/app/_components/shareButton/ClipBoardButton.tsx
  src/app/_components/shareButton/KakaoShareButton.tsx
  src/app/_components/shareButton/clipBoardButton.module.scss
  src/app/_components/shareButton/kakaoShareButton.module.scss
  src/app/globals.css
  src/data/regionList.json
  src/middleware.ts
  yarn.lock
Labels: 💄 UI

#57 [feat/used-list] 카테고리 필터링, 거래중/거래완료 개선, 페이지네이션 추가
  src/apis/goods.ts
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/_components/CustomSelect.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsFilter.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsSearch.tsx
  src/app/(providers)/used-goods/_components/usedGoodsFilter.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsItem.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsList.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsOrder.module.scss
  src/app/(providers)/used-goods/page.module.scss
  src/app/(providers)/used-goods/page.tsx
  src/hooks/useQueryParam.ts
Labels: ✨ 기능, 🎨 코드 개선, 💄 UI

#60 [Feat/stray dog] 분기처리, 유기견 공고페이지 필터링
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/page.tsx
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/middleware.ts
Labels: ✨ 기능, 📈 깃

#62 [feat/deploy] yarn build 오류 수정
  src/apis/stray.ts
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/layout.tsx
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/usedGoodsItem.module.scss
  src/app/(providers)/used-goods/actions.ts
  src/app/(providers)/used-goods/page.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/globals.css
Labels: 🐛 버그, 🔥 삭제, 🚀 배포

#65 [hotfix/deploy] import 대소문자 구분
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
Labels: 🐛 버그

#66 [hoxfix/deploy] 채팅하기 오류 주석처리
  src/app/(providers)/used-goods/[id]/page.tsx
Labels: 🐛 버그

#67 [chore/path] 폰트 이름 변경과 로고 경로 수정
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/_components/kakaoMap/kakaoMapMarker.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/app/globals.css
Labels: 🚑️ 핫픽스, 🔧 설정

#68 [chore/etc] 배포 환경에서 오류 수정 후 develop 브랜치에 병합
  src/app/_components/kakaoMap/kakaoMapMarker.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/app/globals.css
Labels: 🚑️ 핫픽스, 🔥 삭제, 💄 UI, 🔧 설정

#69 [feat/used-goods] 중고 물품 목록 이슈 해결
  src/apis/goods.ts
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/usedGoodsList.module.scss
  src/app/(providers)/used-goods/page.tsx
Labels: 🐛 버그, 💄 UI

#70 [feat/used-goods] 중고 물품 목록 및 상세 페이지 이슈 해결
  src/apis/goods.ts
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/usedGoodsList.module.scss
  src/app/(providers)/used-goods/page.tsx
Labels: 🐛 버그, 💄 UI, 🚀 배포

#72 [feat/wishLike] 찜, 좋아요 기능 구현
  src/apis/goods.ts
  src/apis/wishLike/actions.ts
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/WishButton.tsx
  src/app/(providers)/used-goods/_components/wishButton.module.scss
Labels: ✨ 기능

#76 [design/nav] 반응형 디자인 구현
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
Labels: ✨ 기능, 💄 UI

#79 [feat/mungsta] 인터셉트 라우트 적용해 상세 모달창 띄우기
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/[id]/update/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/@modal/default.tsx
  src/app/(providers)/layout.tsx
  src/app/(providers)/mungstagram/[id]/page.tsx
  src/app/(providers)/mungstagram/[id]/update/page.tsx
  src/app/(providers)/mungstagram/create/page.tsx
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/app/_components/layout/Main.tsx
  src/app/_components/layout/index.ts
  src/app/_components/layout/main.module.scss
Labels: ✨ 기능, 💄 UI

#80 [feat/chatting] 실시간 채팅
  src/apis/chat/chat.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/chatting/Chat.tsx
  src/app/_components/chatting/ChatInput.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/ChatListContent.tsx
  src/app/_components/chatting/ChatModal.tsx
  src/app/_components/chatting/UsedItemData.tsx
  src/app/_components/chatting/chatInput.module.scss
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/chatting/chatListContent.module.scss
  src/app/_components/chatting/chatModal.module.scss
  src/app/_components/chatting/usedItemData.module.scss
  src/app/_components/layout/Header.tsx
  src/shared/supabase/types/supabase.d.ts
Labels: ✨ 기능, 📈 깃

#81 [feat/chatting] 실시간 채팅
  src/app/_components/chatting/Chat.tsx
  src/app/_components/chatting/ChatInput.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/ChatListContent.tsx
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/layout/Header.tsx
Labels: 🐛 버그, ✨ 기능

#82 [feat/responsive] 네비 반응형 수정 및 디자인 변경으로 인한 등록,수정페이지 변
  src/app/(providers)/used-goods/create/CreateForm.tsx
  src/app/(providers)/used-goods/create/create.module.scss
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
  src/app/(providers)/used-goods/update/[id]/update.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
Labels: ✨ 기능, 💄 UI

#84 [Feat/stray-dog] 버튼 클릭시 검색값 출력
  package.json
  public/images/default_avatar.webp
  src/_middleware.ts
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/_route.ts
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/layout.tsx
  src/app/(providers)/page.tsx
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/create/CreateForm.tsx
  src/app/_components/layout/Header.tsx
  src/middleware.ts
  src/shared/AuthProvider.tsx
  src/shared/PrivateRouteWrapper.tsx
  src/shared/PublicRouteWrapper.tsx
  yarn.lock
Labels: ✨ 기능, 📈 깃

#85 [feat/chatting] 실시간 채팅
  src/apis/chat/chat.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/chatting/Chat.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/ChatListContent.tsx
  src/app/_components/chatting/UsedItemData.tsx
  src/app/_components/chatting/chat.module.scss
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/chatting/chatListContent.module.scss
  src/app/_components/chatting/usedItemData.module.scss
  src/shared/supabase/types/supabase.d.ts
Labels: ✨ 기능, 💄 UI

#86 [feat/chatting] 중고물품 상세페이지 채팅 쿼리 오류 해결
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/ChatListContent.tsx
Labels: 🐛 버그

#87 [feat/mungsta] 멍스타그램 게시글 작성 후 목록 표시
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/shared/supabase/types/supabase.d.ts
Labels: ✨ 기능, 💄 UI

#88 [Feat/login] 로그인 후 마이페이지/글 작성페이지에서 새로고침 시 튕기는 오류 해결
  next.config.js
  src/_middleware.ts
  src/apis/auth/callback/route.ts
  src/apis/auth/route.ts
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/create/CreateForm.tsx
  src/app/(providers)/used-goods/create/page.tsx
  src/hooks/useAuth.ts
  src/middleware.ts
  src/shared/AuthProvider.tsx
  src/shared/PrivateRouteWrapper.tsx
  src/shared/PublicRouteWrapper.tsx
Labels: 🐛 버그

#89 [feat/alarm] 찜 알림기능 구현
  next.config.js
  src/apis/alertMessage.ts
  src/apis/goods.ts
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/WishButton.tsx
  src/app/_components/alertMessage/AlertMessageList.tsx
  src/app/_components/alertMessage/AlertMessageRow.tsx
  src/app/_components/alertMessage/alertMessageList.module.scss
  src/app/_components/alertMessage/alertMessageRow.module.scss
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/app/_components/main/MainGrid.tsx
  src/hooks/useAlertMessage.ts
  src/hooks/useToast.ts
  src/shared/supabase/types/supabase.d.ts
  src/utils/ReactQueryProviders.tsx
Labels: 🐛 버그, ✨ 기능

#90 [feat/mungsta] 멍스타그램 목록 UI 개선 및 반응형 적용
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/SlideImage.tsx
  src/app/(providers)/used-goods/_components/slideImage.module.scss
  src/app/(providers)/used-goods/page.module.scss
  src/app/_components/layout/main.module.scss
  src/app/layout.tsx
  src/shared/modal.ts
Labels: ✨ 기능, 💄 UI

#92 [design/my-page] 마이페이지 UI 및 중고거래데이터 불러오기
  src/apis/used-goods/actions.ts
  src/apis/wishLike/actions.ts
  src/app/(providers)/profile/[userId]/page.module.scss
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/profile/_components/Card.tsx
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/profile/_components/Profile.tsx
  src/app/(providers)/profile/_components/card.module.scss
  src/app/(providers)/profile/_components/list.module.scss
  src/app/(providers)/profile/_components/profile.module.scss
  src/app/(providers)/used-goods/create/_components/CreateForm.tsx
  src/app/(providers)/used-goods/create/_components/create.module.scss
  src/app/(providers)/used-goods/create/page.tsx
  src/app/_components/layout/header.module.scss
  src/app/variables.css
  src/shared/PrivateRouteWrapper.tsx
Labels: ✨ 기능, 💄 UI

#93 [feat/chatting] 실시간 채팅 알림기능
  src/apis/alertMessage.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/alertMessage/AlertMessageList.tsx
  src/app/_components/chatting/ChatInput.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/UsedItemData.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/hooks/useAlertMessage.ts
Labels: ✨ 기능

#94 [Feat/login] login/signup 페이지 UI 수정
  public/images/sadpug.png
  public/images/sadpugtext.png
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/stray-dogs/_component/NoSearchValue.tsx
  src/app/(providers)/stray-dogs/_component/noSearchValue.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/create/page.tsx
Labels: 📈 깃, 💄 UI

#97 [feat/wishLike] 좋아요 기능 구현
  src/apis/mung-stagram/action.ts
  src/apis/wishLike/actions.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/_components/LikeButton.tsx
  src/utils/table.ts
Labels: ✨ 기능

#95 [feat/used-goods] 중고 물품 목록 페이지네이션 수정 및 반응형
  src/apis/goods.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/usedGoodsList.module.scss
  src/app/(providers)/used-goods/page.module.scss
Labels: ✨ 기능, 💄 UI

#101 [feat/profile] 프로필 수정
  src/apis/profile/profile.ts
  src/app/(providers)/profile/_components/Profile.tsx
Labels: ✨ 기능

#102 [Feat/login] 소셜로그인 오류 수정
  package.json
  src/_middleware.ts
  src/apis/auth/callback/route.ts
  src/apis/auth/route.ts
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/layout.tsx
  src/app/_components/layout/Header.tsx
  src/shared/AuthProvider.tsx
  src/shared/PrivateRouteWrapper.tsx
  src/shared/PublicRouteWrapper.tsx
  yarn.lock
Labels: 🐛 버그

#103 [feat/facilities] 동반시설 마커 추가수정, 중고거래 상세 편집버튼
  src/apis/alertMessage.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/_components/LikeButton.tsx
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/WishButton.tsx
  src/app/(providers)/used-goods/update/[id]/update.module.scss
  src/app/_components/alertMessage/AlertMessageRow.tsx
  src/app/_components/pagination/pagination.module.scss
  src/hooks/useAlertMessage.ts
Labels: ✨ 기능, ⚡️ 성능 개선

#107 [feat/my-page] 마이페이지, 헤더
  public/images/my_page_default.svg
  src/apis/mung-stagram/action.ts
  src/apis/wishLike/actions.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/mungstagram/page.tsx
  src/app/(providers)/profile/_components/Card.tsx
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/profile/_components/MungstaCard.tsx
  src/app/(providers)/profile/_components/Profile.tsx
  src/app/(providers)/profile/_components/card.module.scss
  src/app/(providers)/profile/_components/list.module.scss
  src/app/(providers)/profile/_components/mungstaCard.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
Labels: ✨ 기능

#109 [feat/alarm] 좋아요, 찜 알림기능 구현
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/profile/_components/Profile.tsx
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/app/_components/main/mainGrid.module.scss
Labels: 🐛 버그, ✨ 기능

#110 [feat/my-page] scss 수정
  src/app/(providers)/profile/_components/Card.tsx
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/profile/_components/card.module.scss
Labels: 🔥 삭제, 💄 UI

#112 [feat/mungsta] 멍스타그램 유효성 검사 & URL 접근 등록 페이지 추가
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/mungstagram/create/page.tsx
Labels: ✨ 기능, 🎨 코드 개선, 💄 UI

#111 [Feat/login] 프로필 기본 이미지 수정
  src/app/(providers)/auth/signup/page.tsx
Labels: 🔥 삭제, 📝 문서

#113 [design/main-reactive] 부분 디자인 통일 및 수정
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/profile/_components/profile.module.scss
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/create/_components/create.module.scss
  src/app/(providers)/used-goods/page.module.scss
  src/app/(providers)/used-goods/update/[id]/update.module.scss
Labels: 💄 UI

#115 [hotfix/redeploy] 2차 배포전 콘솔정리
  src/app/(providers)/auth/login/page.tsx
  src/app/_components/layout/Header.tsx
Labels: 🚑️ 핫픽스

#118 [fix/stray-dog] hotfix: onSubmit 다시 생성
  src/app/(providers)/stray-dogs/page.tsx
Labels: 🚑️ 핫픽스

#119 [fix/stray dog] 누락된 onsubmit 생성
  src/app/(providers)/stray-dogs/page.tsx
Labels: 🚑️ 핫픽스

#120 [feat/chatting] 채팅
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/chatList.module.scss
Labels: 💄 UI

#121 [Feat/login] 기본이미지 변경, 회원가입 오류메세지 수정
  src/app/(providers)/auth/signup/page.tsx
Labels: 🎨 코드 개선

#126 [feat/facilities] 동반시설페이지 기능수정
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/_components/alertMessage/alertMessageList.module.scss
  src/app/_components/facilities/NearFacilities.tsx
  src/app/_components/facilities/nearFacilities.module.scss
Labels: ⚡️ 성능 개선

#128 [feat/responsive] 반응형 구현
  src/app/(providers)/profile/[userId]/page.module.scss
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/profile/_components/card.module.scss
  src/app/(providers)/profile/_components/list.module.scss
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/(providers)/used-goods/create/_components/CreateForm.tsx
  src/app/(providers)/used-goods/create/_components/create.module.scss
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
  src/app/(providers)/used-goods/update/[id]/update.module.scss
  src/app/_components/kakaoMap/kakaoMapMarker.module.scss
Labels: 🔥 삭제, ✨ 기능, 💄 UI

#129 [feat/used-goods] 견종 사이즈 다중 선택 및 추가 작업
  package.json
  src/apis/goods.ts
  src/app/(providers)/used-goods/_components/CustomSelect.tsx
  src/app/(providers)/used-goods/_components/Dropdown.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsFilter.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsSearch.tsx
  src/app/(providers)/used-goods/_components/config/selectConfig.ts
  src/app/(providers)/used-goods/_components/dropdown.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsFilter.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsList.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsOrder.module.scss
  src/app/(providers)/used-goods/_components/usedGoodsSearch.module.scss
  src/app/(providers)/used-goods/page.module.scss
  src/app/(providers)/used-goods/page.tsx
  src/app/variables.css
  src/hooks/useQueryParam.ts
  yarn.lock
Labels: 🔥 삭제, ✨ 기능, 💄 UI, 🔧 설정

#130 [design/responsive-design] 메인, 동반시설 반응형작업
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/images/iphone.png
  public/images/logo.png
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/page.module.scss
  src/app/(providers)/profile/_components/profile.module.scss
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/create/_components/create.module.scss
  src/app/(providers)/used-goods/update/[id]/update.module.scss
  src/app/_components/facilities/nearFacilities.module.scss
  src/app/_components/layout/Footer.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/footer.module.scss
  src/app/_components/layout/header.module.scss
  src/app/_components/layout/loading/loading.module.scss
  src/app/_components/main/MainGrid.tsx
  src/app/_components/main/mainGrid.module.scss
  src/app/favicon.ico
  src/app/layout.tsx
Labels: 💄 UI

#132 [Feat/login] 회원가입시 파일용량 제한, 실시간 유효성 검사 수정
  src/app/(providers)/auth/login/page.module.scss
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
Labels: 🐛 버그, ✨ 기능, 📈 깃

#133 [feat/stray dog] 유기견 공고 목록 반응형 구현
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/(providers)/stray-dogs/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/create/_components/CreateForm.tsx
  src/shared/PublicRouteWrapper.tsx
  src/shared/_AuthProvider.tsx
Labels: 🎨 코드 개선, 💄 UI

#136 [feat/my-page] 데이터 없을 때 화면 표시
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/profile/_components/list.module.scss
  src/app/_components/shareButton/KakaoShareButton.tsx
Labels: ✨ 기능
