Repository nbcamp-mot/puppy-ground, pull requests merged in 2024-02, with the labels that each got.

#137 [feat/stray dog] 유기견 공고 상세 페이지 반응형
  src/app/(providers)/stray-dogs/[desertionNo]/page.module.scss
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
Labels: 💄 UI

#139 [refactor/kakaoshare] 카카오톡 공유 리팩토링
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/stray-dogs/[desertionNo]/page.module.scss
  src/app/(providers)/stray-dogs/[desertionNo]/page.tsx
  src/app/(providers)/used-goods/[id]/page.module.scss
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/shareButton/KakaoShareButton.tsx
  src/app/_components/shareButton/kakaoShareButton.module.scss
Labels: 🎨 코드 개선

#141 [feat/chatting] 채팅 반응형 구현
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/ChatModal.tsx
  src/app/_components/chatting/chatInput.module.scss
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/chatting/chatModal.module.scss
  src/app/_components/chatting/usedItemData.module.scss
Labels: 💄 UI

#145 [fix/profile] 로그아웃 후 로그인 했을 때 프로필 오류
  src/app/(providers)/profile/_components/Profile.tsx
Labels: 🐛 버그

#147 [feat/chatting] 채팅 개선
  src/apis/chat/chat.ts
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/chatting/ChatInput.tsx
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/ChatListContent.tsx
  src/app/_components/chatting/ChatModal.tsx
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/chatting/chatModal.module.scss
  src/app/_components/chatting/usedItemData.module.scss
  src/app/_components/layout/Header.tsx
  src/hooks/useChat.ts
  src/shared/zustand/ChatStore.ts
  yarn.lock
Labels: 🎨 코드 개선, 📈 깃, 💄 UI

#150 [feat/login] 분기처리 로직 middleware로 수정
  package.json
  src/app/(providers)/auth/api/callback/route.ts
  src/app/(providers)/auth/login/_components/LoginPage.tsx
  src/app/(providers)/auth/login/_components/page.module.scss
  src/app/(providers)/auth/login/page.tsx
  src/app/(providers)/auth/signup/_componenets/SignUp.tsx
  src/app/(providers)/auth/signup/_componenets/page.module.scss
  src/app/(providers)/auth/signup/page.tsx
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/used-goods/create/page.tsx
  src/app/_components/layout/Header.tsx
  src/middleware.ts
  src/shared/PrivateRouteWrapper.tsx
  src/shared/_AuthProvider.tsx
  src/shared/supabase/supabase.ts
  yarn.lock
Labels: 🎨 코드 개선, 📈 깃

#151 [design/chatting] 채팅
  src/app/_components/chatting/ChatList.tsx
  src/app/_components/chatting/chatList.module.scss
Labels: 💄 UI

#152 [feat/comment] 멍스타그램 댓글 구현
  src/apis/mung-stagram/action.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/_components/CommentForm.tsx
  src/app/(providers)/@modal/_components/CommentList.tsx
  src/app/(providers)/@modal/_components/commentList.module.scss
  src/app/(providers)/@modal/_components/commetForm.module.scss
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
  src/app/_components/shareButton/kakaoShareButton.module.scss
  src/shared/supabase/types/supabase.d.ts
Labels: ✨ 기능, 💄 UI

#156 [fix/deploy] 카카오맵 주소 수정
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/alertMessage/AlertMessageList.tsx
  src/app/_components/facilities/FacilitiesMapComponent.tsx
  src/app/layout.tsx
  src/hooks/useDebounce.ts
Labels: 🐛 버그

#157 [fix/deploy] v1.3.1 배포
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/_components/alertMessage/AlertMessageList.tsx
  src/app/_components/facilities/FacilitiesMapComponent.tsx
  src/app/layout.tsx
  src/hooks/useDebounce.ts
Labels: 🚀 배포

#159 [fix/map] v1.3.2 배포
  src/app/layout.tsx
Labels: 🚀 배포

#161 [fix/deploy] v1.3.3 배포
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/page.tsx
  src/app/_components/facilities/FacilitiesMapComponent.tsx
  src/app/_components/facilities/facilitiesMapComponent.module.scss
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/_components/kakaoMap/kakaoMapMarker.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/shareButton/KakaoShareButton.tsx
  src/app/layout.tsx
  src/middleware.ts
Labels: 🚀 배포

#162 [fix/deploy] 지도 오류수정
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/page.tsx
  src/app/_components/facilities/FacilitiesMapComponent.tsx
  src/app/_components/facilities/facilitiesMapComponent.module.scss
  src/app/_components/kakaoMap/KakaoMapMarker.tsx
  src/app/_components/kakaoMap/kakaoMapMarker.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/shareButton/KakaoShareButton.tsx
  src/app/layout.tsx
  src/middleware.ts
Labels: 🐛 버그

#166 [fix/deploy] 지도 오류 원인 해결
  src/app/(providers)/layout.tsx
  src/app/_components/layout/Header.tsx
Labels: 🐛 버그, 🚀 배포

#165 [fix/deploy] 카카오 맵 오류 원인 해결
  src/app/(providers)/layout.tsx
  src/app/_components/layout/Header.tsx
Labels: 🐛 버그, 🚀 배포

#167 [feat/mungsta] 멍스타그램 개선
  package.json
  src/apis/mung-stagram/action.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/@modal/_components/CommentForm.tsx
  src/app/(providers)/@modal/_components/index.ts
  src/app/(providers)/mungstagram/[id]/page.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaPost.tsx
  src/app/(providers)/mungstagram/_components/detail/mungstaPost.module.scss
  src/app/(providers)/mungstagram/_components/root/MungstaPosts.tsx
  src/app/(providers)/mungstagram/_components/root/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/app/_components/lib/ImageSlider.tsx
  src/app/_components/lib/getQueryClient.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/shared/constant/constant.ts
  src/shared/modal.ts
  src/utils/file.ts
  yarn.lock
Labels: 🐛 버그, ✨ 기능, 🎨 코드 개선, 💄 UI

#168 [design/chatting] 채팅 css 변경
  src/app/_components/chatting/chatList.module.scss
Labels: 💄 UI

#171 [refactor/optimization] 기본이미지 svg로 변경
  public/images/my_page_default.svg
  public/images/sadpug (1).svg
  public/next.svg
  public/vercel.svg
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
Labels: ⚡️ 성능 개선

#173 chore: body에 폰트 적용 (#172)
  src/app/globals.css
Labels: 💄 UI

#174 [feat/chatting] 불필요한 코드 제거
  src/app/_components/layout/Header.tsx
Labels: 🎨 코드 개선

#175 [refactor/optimization] 댓글 수정
  src/app/(providers)/@modal/_components/CommentForm.tsx
  src/app/(providers)/@modal/_components/commentList.module.scss
Labels: ✨ 기능, 💄 UI

#169 [deploy/v1.3.5] v1.3.5 배포
  package.json
  public/images/my_page_default.svg
  public/images/sadpug (1).svg
  public/next.svg
  public/vercel.svg
  src/apis/mung-stagram/action.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/@modal/_components/CommentForm.tsx
  src/app/(providers)/@modal/_components/commentList.module.scss
  src/app/(providers)/@modal/_components/index.ts
  src/app/(providers)/mungstagram/[id]/page.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaPost.tsx
  src/app/(providers)/mungstagram/_components/detail/mungstaPost.module.scss
  src/app/(providers)/mungstagram/_components/root/MungstaPosts.tsx
  src/app/(providers)/mungstagram/_components/root/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/app/(providers)/profile/_components/List.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsList.tsx
  src/app/_components/chatting/chatList.module.scss
  src/app/_components/layout/Header.tsx
  src/app/_components/lib/ImageSlider.tsx
  src/app/_components/lib/getQueryClient.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/shared/constant/constant.ts
  src/shared/modal.ts
  src/utils/file.ts
  yarn.lock
Labels: 🚀 배포

#177 [chore/supabase] supabase 이동
  next.config.js
Labels: 📝 문서

#180 [refactor/profile] profile 코드 개선
  src/app/(providers)/profile/_components/Profile.tsx
  src/hooks/useProfile.ts
  src/hooks/useUploadImage.ts
Labels: 🎨 코드 개선

#181 [feat/mungsta] 멍스타그램 상세페이지 반응형
  src/app/(providers)/@modal/_components/commentList.module.scss
  src/app/(providers)/mungstagram/_components/detail/MungstaPost.tsx
  src/app/(providers)/mungstagram/_components/detail/mungstaPost.module.scss
Labels: ✨ 기능, 💄 UI

#182 [feat/mungsta] 멍스타그램 반응형 개선 & 등록 페이지 나가면 입력 초기화
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaPost.tsx
  src/app/(providers)/mungstagram/_components/detail/mungstaPost.module.scss
Labels: 🐛 버그, 🎨 코드 개선, 💄 UI

#183 [refactor/profile] 프로필 코드 버그 수정
  src/app/(providers)/profile/_components/Profile.tsx
  src/hooks/useUploadImage.ts
Labels: 🎨 코드 개선

#185 [fix/hydration] hydration 에러 수정
  src/app/(providers)/@modal/_components/CommentList.tsx
  src/app/(providers)/profile/_components/Card.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsItem.tsx
Labels: 🐛 버그

#186 [refactor/optimization] 중고거래 추가 기능
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/create/_components/CreateForm.tsx
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
Labels: ✨ 기능

#187 [refactor/modify] facilities 훅 생성 및 코드개선
  public/images/family.webp
  public/images/hotel.webp
  public/images/mungstagram.webp
  public/images/restaurant.webp
  public/images/toy.webp
  public/images/travel.webp
  public/images/walk.webp
  public/images/welsh.webp
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/facilities/page.tsx
  src/app/_components/facilities/CurrentLocationButton.tsx
  src/app/_components/facilities/FacilitiesMapComponent.tsx
  src/app/_components/facilities/FacilitiesOverlay.tsx
  src/app/_components/facilities/NearFacilities.tsx
  src/app/_components/facilities/currentLocationButton.module.scss
  src/app/_components/facilities/facilitiesMapComponent.module.scss
  src/app/_components/facilities/facilitiesOverlay.module.scss
  src/app/_components/main/MainGrid.tsx
  src/hooks/useCurrentLocation.ts
  src/hooks/useMapBounds.ts
  src/middleware.ts
Labels: 🎨 코드 개선

#190 [feat/stray dog] 유기견 공고 목록 반응형 수정, 코드 수정
  public/images/default_avatar.webp
  public/images/sadpugtext.png
  public/images/sadpugtext.webp
  src/app/(providers)/stray-dogs/_component/NoSearchValue.tsx
  src/app/(providers)/stray-dogs/_component/StryaDogs.tsx
  src/app/(providers)/stray-dogs/_component/noSearchValue.module.scss
  src/app/(providers)/stray-dogs/_component/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/hooks/stray-dog/useCityAndGu.ts
  src/hooks/stray-dog/useStrayListFilter.ts
  src/middleware.ts
Labels: 🎨 코드 개선, 💄 UI

#192 [design/notFound] 404 페이지 UI
  src/app/not-found.module.scss
  src/app/not-found.tsx
Labels: 💄 UI

#193 [feat/mungsta] 멍스타그램 게시글 수정, 삭제
  src/apis/mung-stagram/action.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/[id]/update/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/mungstagram/[id]/update/page.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaModal.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaPost.tsx
  src/app/(providers)/mungstagram/_components/detail/mungstaModal.module.scss
  src/app/(providers)/mungstagram/_components/detail/mungstaPost.module.scss
  src/utils/file.ts
Labels: ✨ 기능, 💄 UI

#184 [deploy/v1.3.6] v1.3.6 배포
  next.config.js
  public/images/default_avatar.webp
  public/images/family.webp
  public/images/hotel.webp
  public/images/mungstagram.webp
  public/images/restaurant.webp
  public/images/sadpugtext.png
  public/images/sadpugtext.webp
  public/images/toy.webp
  public/images/travel.webp
  public/images/walk.webp
  public/images/welsh.webp
  src/apis/mung-stagram/action.ts
  src/app/(providers)/@modal/(.)mungstagram/[id]/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/[id]/update/page.tsx
  src/app/(providers)/@modal/(.)mungstagram/create/page.module.scss
  src/app/(providers)/@modal/(.)mungstagram/create/page.tsx
  src/app/(providers)/@modal/_components/CommentList.tsx
  src/app/(providers)/@modal/_components/commentList.module.scss
  src/app/(providers)/facilities/page.module.scss
  src/app/(providers)/facilities/page.tsx
  src/app/(providers)/mungstagram/[id]/update/page.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaModal.tsx
  src/app/(providers)/mungstagram/_components/detail/MungstaPost.tsx
  src/app/(providers)/mungstagram/_components/detail/mungstaModal.module.scss
  src/app/(providers)/mungstagram/_components/detail/mungstaPost.module.scss
  src/app/(providers)/profile/_components/Card.tsx
  src/app/(providers)/profile/_components/Profile.tsx
  src/app/(providers)/stray-dogs/_component/NoSearchValue.tsx
  src/app/(providers)/stray-dogs/_component/StryaDogs.tsx
  src/app/(providers)/stray-dogs/_component/noSearchValue.module.scss
  src/app/(providers)/stray-dogs/_component/page.module.scss
  src/app/(providers)/stray-dogs/page.tsx
  src/app/(providers)/used-goods/[id]/page.tsx
  src/app/(providers)/used-goods/_components/UsedGoodsItem.tsx
  src/app/(providers)/used-goods/create/_components/CreateForm.tsx
  src/app/(providers)/used-goods/update/[id]/UpdateForm.tsx
  src/app/_components/facilities/CurrentLocationButton.tsx
  src/app/_components/facilities/FacilitiesMapComponent.tsx
  src/app/_components/facilities/FacilitiesOverlay.tsx
  src/app/_components/facilities/NearFacilities.tsx
  src/app/_components/facilities/currentLocationButton.module.scss
  src/app/_components/facilities/facilitiesMapComponent.module.scss
  src/app/_components/facilities/facilitiesOverlay.module.scss
  src/app/_components/main/MainGrid.tsx
  src/app/not-found.module.scss
  src/app/not-found.tsx
  src/hooks/stray-dog/useCityAndGu.ts
  src/hooks/stray-dog/useStrayListFilter.ts
  src/hooks/useCurrentLocation.ts
  src/hooks/useMapBounds.ts
  src/hooks/useProfile.ts
  src/hooks/useUploadImage.ts
  src/middleware.ts
  src/utils/file.ts
Labels: 🚀 배포

#194 [feat/chatting] 판매완료 실종 해결
  src/app/_components/chatting/UsedItemData.tsx
Labels: 🐛 버그

#197 [feat/header] header, main 코드 개선
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/app/_components/main/MainGrid.tsx
  src/app/_components/main/mainGrid.module.scss
Labels: ⚡️ 성능 개선, 🎨 코드 개선

#198 [feat/login] 유저정보 변경에 따른 헤더 변경 로직 수정
  public/images/sadpugtext.svg
  src/app/(providers)/auth/signup/_componenets/SignUp.tsx
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/used-goods/create/page.tsx
  src/app/_components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/hooks/useStrayDog.ts
  src/shared/PrivateRouteWrapper.tsx
  src/shared/PublicRouteWrapper.tsx
Labels: 🔥 삭제

#199 [feat/stray dog] 유기견 공고 목록 반응형 수정, api오류시 나타나는 화면 수정
  public/images/sadpugtext.svg
  src/app/(providers)/auth/signup/_componenets/SignUp.tsx
  src/app/(providers)/profile/[userId]/page.tsx
  src/app/(providers)/stray-dogs/_component/Error.module.scss
  src/app/(providers)/stray-dogs/_component/Error.tsx
  src/app/(providers)/stray-dogs/_component/StryaDogs.tsx
  src/app/(providers)/stray-dogs/_component/page.module.scss
  src/app/(providers)/used-goods/create/page.tsx
  src/app/_components/chatting/UsedItemData.tsx
  src/app/_components/layout/Header.tsx
  src/app/_components/layout/header.module.scss
  src/app/_components/main/MainGrid.tsx
  src/app/_components/main/mainGrid.module.scss
  src/hooks/useAuth.ts
  src/hooks/useStrayDog.ts
  src/shared/PrivateRouteWrapper.tsx
  src/shared/PublicRouteWrapper.tsx
Labels: 💄 UI

#202 [fix/mungsta] 멍스타그램 쿼리키 수정 및 메인 최소 높이 지정
  src/app/(providers)/mungstagram/_components/root/MungstaPosts.tsx
  src/app/(providers)/mungstagram/_components/root/page.module.scss
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/app/_components/layout/main.module.scss
Labels: 🎨 코드 개선, 💄 UI

#203 [deploy/v1.3.7] v1.3.7 배포
  README.md
  src/app/(providers)/mungstagram/_components/root/MungstaPosts.tsx
  src/app/(providers)/mungstagram/_components/root/page.module.scss
  src/app/(providers)/mungstagram/page.module.scss
  src/app/(providers)/mungstagram/page.tsx
  src/app/_components/layout/main.module.scss
Labels: 🚀 배포

#205 [fix/header] 헤더 Layout Shift 해결
  src/app/(providers)/layout.tsx
  src/app/_components/layout/loading/HeaderLoading.tsx
  src/app/_components/layout/loading/headerLoading.module.scss
Labels: 🎨 코드 개선, 💄 UI

#206 [deploy/v1.3.8] v1.3.8 배포
  src/app/(providers)/layout.tsx
  src/app/_components/layout/loading/HeaderLoading.tsx
  src/app/_components/layout/loading/headerLoading.module.scss
Labels: 🚀 배포
